services:
  - type: web
    name: yuwaatech
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://yuwaatech.onrender.com
