services:
  - type: web
    name: yuwaatech-laravel
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev
      mkdir -p database
      touch database/database.sqlite
      php artisan config:clear
      php artisan cache:clear
      php artisan key:generate --force
      php artisan migrate --force
      npm install
      npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
    staticPublishPath: public
